spring.application.name=BFF_Web
server.port=8080

# Habilitar el manejo de Circuit Breaker en Feign
feign.circuitbreaker.enabled=true

# Tamaño de la ventana deslizante
resilience4j.circuitbreaker.instances.assessmentService.slidingWindowSize=10
# Porcentaje de fallo para abrir el circuito (Si el 50% o más de las últimas 10 llamadas fallan, se corta)
resilience4j.circuitbreaker.instances.assessmentService.failureRateThreshold=50
# Tiempo en milisegundos que el circuito permanecerá ABIERTO antes de intentar reconectar (10 segundos)
resilience4j.circuitbreaker.instances.assessmentService.waitDurationInOpenState=10000
# Número de llamadas permitidas en estado SEMI-ABIERTO para verificar si el microservicio se recuperó
resilience4j.circuitbreaker.instances.assessmentService.permittedNumberOfCallsInHalfOpenState=3

# Configuración de Swagger
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operationsSorter=method