spring.application.name=Assessment_Manager
server.port=8082

# Configuración de la URL de conexión
spring.datasource.url=jdbc:mariadb://localhost:3306/assessment_manager_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Estas URLs apuntan a los otros microservicios que creamos
external.services.student-url=http://localhost:8081
external.services.academic-url=http://localhost:8083

# Circuit Breaker para Estudiantes
resilience4j.circuitbreaker.instances.studentServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.studentServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.studentServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.studentServiceCB.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.studentServiceCB.permittedNumberOfCallsInHalfOpenState=3

# Circuit Breaker para Académico
resilience4j.circuitbreaker.instances.academicServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.academicServiceCB.slidingWindowSize=6
resilience4j.circuitbreaker.instances.academicServiceCB.failureRateThreshold=40
resilience4j.circuitbreaker.instances.academicServiceCB.waitDurationInOpenState=15s
resilience4j.circuitbreaker.instances.academicServiceCB.permittedNumberOfCallsInHalfOpenState=2

# Configuración de Swagger
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operationsSorter=method